Add MacCamy-Fuchs and Cd correction options
Total-RD/seahowl pull request #128
Opened 2024-10-28 16:35 UTC by mattcapa

This PR adds optional corrections as follows:
- MacCamy-Fuchs correction for large cylinders
- Cd correction for large cylinders

2024-10-30 09:56 UTC, tridelat commented
Adding some details on the workflow of this PR for the record.
Since the MacCamy-Fuchs correction tables depend on wave peak period and need to be generated only once, only one correction table object is declared and instantiated with `extern` (essentially acting as a singleton), and is accessible from the the seahowl::hydro namespace.
When environmental conditions are generated, the wave peak period of the waves (if any) is associated to the correction table. The added mass / drag coefficients are then interpolated by calling the table with the Morison node diameters iff diameters are large enough and fluid density is above a certain threshold (set to 500.0 here, meaning that no correction is made if the Morison node is in the air phase).

2024-10-30 10:17 UTC, tridelat requested changes

2024-10-30 10:17 UTC, tridelat commented on include/seahowl/aero/tower_aero.h
> +    bool use_Cd_correction;
Initialize variable for use_Cd_correction (true/false). Maybe both variables should be initialized at false to force user to explicitly activate it in .json/python?

2024-10-30 10:17 UTC, tridelat commented on include/seahowl/env/wave_models.h
> +    bool MacCamyFuchsflag = true;
variable not used, can be removed (the flag is on the tower)

2024-10-30 10:17 UTC, tridelat commented on src/hydro/mooring_hydro.cpp
> +    coefficients.use_MacCamyFuchs_correction = false;
add explicitly coefficients.use_Cd_correction = false;

2024-10-30 19:18 UTC, mattcapa commented on include/seahowl/aero/tower_aero.h
> +    bool use_Cd_correction;
I propose to initialize both with true.. I think those corrections should the norm. 
A user aiming at testing a specific Cd or Cm, it should force the flags to false.

2024-10-30 19:19 UTC, mattcapa commented on include/seahowl/env/wave_models.h
> +    bool MacCamyFuchsflag = true;
very good check ;)

2024-10-30 19:20 UTC, mattcapa commented on src/hydro/mooring_hydro.cpp
> +    coefficients.use_MacCamyFuchs_correction = false;
ok

2024-10-31 08:46 UTC, tridelat commented on include/seahowl/aero/tower_aero.h
> +    bool use_Cd_correction;
Okay, let's keep it this way

2024-10-31 08:48 UTC, tridelat approved these changes
Good to go, thanks!

2024-10-31 17:25 UTC, merged