Specify an output.csv file for each turbine in multiturbines
Total-RD/seahowl pull request #56
Opened 2023-03-13 17:03 UTC by wenchaoyu

This PR serves to specify an output.csv file for each single turbine in multiturbines case.

2023-03-13 18:32 UTC, tridelat requested changes

2023-03-13 18:32 UTC, tridelat commented on src/io/write_csv.cpp
> +        std::string filename_turbine = filename + "output_" + "T" + std::to_string(idx_turbine) + ".csv";
Calling it "turbine" might be clearer instead of "T" as it's in the file name (it was T before because variable names would be long otherwise). And make `filename` as `fileprefix` where the "output_" prefix is defined outside (in main.cpp here) and passed here or drop it completely (remove `filename` in the function signature).

2023-03-13 20:01 UTC, wenchaoyu commented on src/io/write_csv.cpp
> +        std::string filename_turbine = filename + "output_" + "T" + std::to_string(idx_turbine) + ".csv";
Changed by following your suggestions. An `if` option is also added, filename will be kept as `output.csv` if single turbine case, and prefix `_turbine` will be specified if multiple turbines case.

2023-03-14 08:34 UTC, tridelat approved these changes
Looks good, thanks!

2023-03-14 10:11 UTC, merged