Separate elasto entities + SystemElasto as shared_ptr
Total-RD/seahowl pull request #59
Opened 2023-03-14 16:11 UTC by tridelat

In this PR:
- Separate elasto entities and components.
- Make SystemElasto shared_ptr and attach to System for convenience (notably for Python wrappers).

2023-03-15 16:56 UTC, wenchaoyu requested changes

2023-03-15 16:56 UTC, wenchaoyu commented on include/seahowl/elasto/blade_elasto.h
> +
remove this empty line

2023-03-15 16:56 UTC, wenchaoyu commented on include/seahowl/elasto/mooring_elasto.h
> +
remove the empty line

2023-03-15 16:56 UTC, wenchaoyu commented on src/main.cpp
> +    std::cout << "time: " << system_elasto->get_time() << ", step: " << step
Can this GetChTime() function be called from system_core, not in system_elasto? (make more senes for me that time is from system_core level, not from system_elasto level)

2023-03-15 16:56 UTC, wenchaoyu commented on tests/unit_tests/test_components.cpp
>  TEST(test_blade, natural_period_dynamic_edge) {
This test doesn't pass on my local, can you have a check on this?
![image](https://user-images.githubusercontent.com/4232919/225383332-14ecf553-9f75-4d1d-9c5b-883b5a483743.png)

2023-03-15 18:38 UTC, tridelat commented on include/seahowl/elasto/blade_elasto.h
> +
Actually this was added on purpose, to separate `#pragma once` from include statements (there might be a lack of consistency across the files about that though)

2023-03-15 18:38 UTC, tridelat commented on include/seahowl/elasto/mooring_elasto.h
> +
Actually this was added on purpose, to separate `#pragma once` from include statements (there might be a lack of consistency across the files about that though)

2023-03-15 18:40 UTC, tridelat commented on tests/unit_tests/test_components.cpp
>  TEST(test_blade, natural_period_dynamic_edge) {
This is due to the default solver options being set in `SystemElastoChrono` now, the timestepper in this case (which wasn't set explicitly in the test previously). Since it is more consistent this way, I changed the expected result of the test (1.356 to 1.343).

2023-03-15 18:48 UTC, tridelat commented on src/main.cpp
> +    std::cout << "time: " << system_elasto->get_time() << ", step: " << step
That makes sense, it's been added now. Behind the hood, the `system_core.get_time` is calling `system_elasto.get_time` since the time stepping is piloted by the elasto part so far.

2023-03-15 19:17 UTC, wenchaoyu commented on tests/unit_tests/test_components.cpp
>  TEST(test_blade, natural_period_dynamic_edge) {
I encounter `Segmentation fault (core dumped)` at the end of the test cases:
- which is not relevant to `test_aerodyn` case, still this error after removing `test_aerodyn` case
- is relevant to `test_multiturbines` case, error dispears after removing this case
Could you have a check on this?

2023-03-15 19:44 UTC, tridelat commented on tests/unit_tests/test_components.cpp
>  TEST(test_blade, natural_period_dynamic_edge) {
This was because `use_aerodyn` was set to true, causing the segfault. Fixed in [098bf3b](https://github.com/Total-RD/seahowl/pull/59/commits/098bf3bb45dc6def2e77d8de401902a54ee0a8b1)

2023-03-15 19:59 UTC, wenchaoyu commented on tests/unit_tests/test_components.cpp
>  TEST(test_blade, natural_period_dynamic_edge) {
`test_multiturbines` failed
![image](https://user-images.githubusercontent.com/4232919/225428140-1eadd940-f6c2-4097-8de0-19767de6f6a9.png)

`test_aerodyn` passed

2023-03-16 07:36 UTC, tridelat commented on tests/unit_tests/test_components.cpp
>  TEST(test_blade, natural_period_dynamic_edge) {
This seemed to be a problem with translation of the rotor when the turbine is assembled AFTER it is translated, this has been fixed now.

2023-03-16 09:29 UTC, wenchaoyu approved these changes
looks good

2023-03-16 10:37 UTC, merged