Refactor core components to use dependency injection
Total-RD/seahowl pull request #65
Opened 2023-03-28 08:55 UTC by tridelat

In this PR, refactoring for:
- Core components now use dependency injection (with the exception of `System`) and must be initialised with references to their aero and elasto counterparts.
- Refactor functions (`initialize`, `build`, etc) in core components to more consistent for easier workflow and maintenance.
- `TurbineElasto` and `TurbineAero` created to handle all their respective elasto and aero logic.
- Move AeroDyn logic from `Turbine` to `TurbineAero`.
- `SystemAero` created and to be attached to `System` (like ` SystemElasto` ).
- read_json now populates existing class instances instead of creating them in function calls
- `std::deque` used instead of `std::vector` in cases where references should not be invalidated with a `push_back` (notably the case for turbines of `SystemElasto` and `SystemAero` that must be referenced in turbines of `System`).
- Switch function signatures expecting `std::shared_ptr` as argument to instead expect `&` (more general) where possible.
- `MeshElasto` attached to `SystemElasto` at construction for convenience.
- Makes `elasto` and `aero` "submodules" completely self-sufficient, no dependency on each other or on `core`, only on `seahowl` main module (such as numerics for `Vector3d`, `Quaternion`, etc)

Nice to do later (possibly in another PR):
- Streamline `System`  workflow (use dependency injection in constructor as well?)
- Formalize further the functions used in core components, as well as elasto components (`build`, `assemble`, etc) and aero components (`compute_aero_loads`)

2023-03-28 11:45 UTC, wenchaoyu requested changes
Regarding HydroChrono, are you going to have similar design for `SystemHydro`, `TurbineHydro`,  `FloaterHydro`, `MooringHydro` etc ?

2023-03-28 11:45 UTC, wenchaoyu commented on include/seahowl/aero/turbine_aero.h
> +     * @param[in] tower_shadow Whether to take tower shadow effect into account or not.
Can you remove the unrelated description here?

2023-03-28 11:45 UTC, wenchaoyu commented on include/seahowl/core/system.h
>      std::shared_ptr<seahowl::aero::WindModel> wind_model;
just a comment, does it make more sense to put wind_model inside the system_aero?

2023-03-28 11:45 UTC, wenchaoyu commented on src/aero/turbine_aero.cpp
> +        rotor.compute_wind_loads_aerodyn(aerodyn->pImpl.MeshFrc, wind_model, time, tower, true, true, true);
Change the function name to `compute_aero_loads`

2023-03-28 11:45 UTC, wenchaoyu commented on src/core/turbine.cpp
> +    rotor.initialize(time, dt);
should we have elasto.initialize(time,dt) here, instead of having rotor and tower seperately? (just be more consistent as aero.initialize)

2023-03-28 11:45 UTC, wenchaoyu commented on src/elasto/rotor_elasto.cpp
> +    system.add(*(body_hub.get()));
Why add body to system in RotorElasto? Is it better in TurbineElasto?

2023-03-28 11:45 UTC, wenchaoyu commented on src/elasto/turbine_elasto.cpp
> +    tower = TowerElasto();
put body = BodyElasto() here

2023-03-28 11:45 UTC, wenchaoyu commented on src/io/read_json.cpp
> +void populate_rotor_elasto_from_json(std::string filepath, seahowl::elasto::RotorElasto& rotor) {
Same comment here, is it possible to move body out of rotor?

2023-03-28 12:45 UTC, tridelat commented on include/seahowl/core/system.h
>      std::shared_ptr<seahowl::aero::WindModel> wind_model;
Yes I think it does, maybe we should do that in another PR when we fix the aero workflow? This PR is already quite heavy.

2023-03-28 12:49 UTC, tridelat commented on src/core/turbine.cpp
> +    rotor.initialize(time, dt);
`initialize` is not called on elasto here, but on the core components.

2023-03-28 12:51 UTC, tridelat commented on src/elasto/rotor_elasto.cpp
> +    system.add(*(body_hub.get()));
Because the body belongs to `RotorElasto`, and you might want to instantiate a `RotorElasto` without a `TurbineElasto`.

2023-03-28 12:52 UTC, tridelat commented on src/elasto/turbine_elasto.cpp
> +    tower = TowerElasto();
Which body? If it is the hub_body, I think it might be better to leave it in `RotorElasto`.

2023-03-28 12:52 UTC, tridelat commented on src/io/read_json.cpp
> +void populate_rotor_elasto_from_json(std::string filepath, seahowl::elasto::RotorElasto& rotor) {
Same comment as above.

2023-03-28 12:59 UTC, tridelat commented on include/seahowl/aero/turbine_aero.h
> +     * @param[in] tower_shadow Whether to take tower shadow effect into account or not.
Done

2023-03-28 13:00 UTC, tridelat commented on src/aero/turbine_aero.cpp
> +        rotor.compute_wind_loads_aerodyn(aerodyn->pImpl.MeshFrc, wind_model, time, tower, true, true, true);
Done

2023-03-28 13:01 UTC, tridelat commented
> Regarding HydroChrono, are you going to have similar design for `SystemHydro`, `TurbineHydro`, `FloaterHydro`, `MooringHydro` etc ?

Not 100% sure yet, definitely a `FloaterHydro` at least for HydroChrono, but at first we might just keep it simple and build up the complexity up to a full `SystemHydro` later if it makes sense.

2023-03-28 13:34 UTC, wenchaoyu requested changes
all tests case passed, seems to be ok. I run the usual validation case with steady inflow 8m/s with shear 0.12 (seahowl ramp + bemt), and here you can see in the following figure, what could be the source of this difference? 
![power_curve](https://user-images.githubusercontent.com/4232919/228356311-3e6ff518-cff1-4b69-a10a-241409554669.png)

2023-03-28 20:10 UTC, wenchaoyu approved these changes
Great work, thanks!

2023-03-29 07:58 UTC, tridelat commented
> all tests case passed, seems to be ok. I run the usual validation case with steady inflow 8m/s with shear 0.12 (seahowl ramp + bemt), and here you can see in the following figure, what could be the source of this difference? ![power_curve](https://user-images.githubusercontent.com/4232919/228356311-3e6ff518-cff1-4b69-a10a-241409554669.png)

Thanks for the very useful comparison graph. Could you run that simulation again and plot the graph again to double check that all is fine in this PR after #66 was merged? (this branch has been rebased since #66 was merged)

2023-03-29 09:01 UTC, wenchaoyu commented
Double checked! PR66 fix it!
![power_curve](https://user-images.githubusercontent.com/4232919/228483006-7b5acc94-4aa0-4bae-851a-2c2f97a935cd.png)

2023-03-29 09:02 UTC, tridelat commented
> Double checked! PR66 fix it! ![power_curve](https://user-images.githubusercontent.com/4232919/228483006-7b5acc94-4aa0-4bae-851a-2c2f97a935cd.png)

That's great, thank you!

2023-03-29 09:03 UTC, merged