Add actuator disk theory as option for 'rotor'
Total-RD/seahowl pull request #87
Opened 2023-09-14 15:22 UTC by mattcapa

Disk theory implemented. Input files changed in order to swith from BEMT to Disk Theory. 
In the inut files, the rotor / type needs to be set on "rigid" for the Disk Theory to be compliant with the Disk Theory hipothesis.

2023-09-22 14:19 UTC, tridelat requested changes
Thanks for this addition! Just a few suggested changes on my side and a test would also be great.

2023-09-22 14:19 UTC, tridelat commented on src/main.cpp
> +
Comments can be removed here

2023-09-22 14:19 UTC, tridelat commented on src/aero/disk.cpp
Nothing happening in this file it seems apart from include statements (all is commented out), you can remove it

2023-09-22 14:19 UTC, tridelat commented on src/aero/rotor_aero.cpp
> +    // Eigen::VectorXd pitch_list;
Remove comments

2023-09-22 14:19 UTC, tridelat commented on src/aero/rotor_aero.cpp
> +
Remove comments

2023-09-22 14:19 UTC, tridelat commented on src/commons/utils.cpp
> +
Remove comments

2023-09-22 14:19 UTC, tridelat commented on src/commons/utils.cpp
> +
Remove comments

2023-09-22 14:19 UTC, tridelat commented on src/io/read_json.cpp
> +    // std::cout<<perf_json.at("infile")<<std::endl;
Remove comment

2023-09-22 14:19 UTC, tridelat commented on src/io/read_rotor_perf.cpp
> +
Remove comment

2023-09-22 14:19 UTC, tridelat commented on src/io/read_rotor_perf.cpp
> +    //	const double PI = 4.0 * atan(1.0);
Remove comment

2023-09-22 14:19 UTC, tridelat commented on src/io/read_rotor_perf.cpp
> +            // std::cout<<line<<std::endl;
Remove comment

2023-09-22 14:19 UTC, tridelat commented on src/io/read_rotor_perf.cpp
> +        // std::cout<<TSROut<<std::endl;
Remove comments

2023-09-22 14:19 UTC, tridelat commented on data/IEA15MW/main.json
Some of the defaults should not be changed here as it is used for tests (unless they still all pass with changes).

2023-09-22 14:19 UTC, tridelat commented on data/IEA15MW/controller/Cp_Ct_Cq.IEA15MW.txt
> +0.0    2.5    3.0    3.5    4.0    4.5    5.0    5.5    6.0    6.5    7.0    7.5    8.0    8.5    9.0    9.5    10.0    10.5    11.0    11.5    12.0    12.5    13.0    13.5    14.0    14.5
Just as a note: we need to be a bit careful here by changing the values here, if there is an interpolation then it will be different as we go from -5deg to -4deg for the pitch over 0 to 2.5 for the TSR instead of 2 to 2.5 for the TSR. It might not be a big problem, but it would be better to actually generate table from TSR=0 if possible.

2023-09-22 14:19 UTC, tridelat commented on data/IEA15MW/main.json
> +      "use_disktheory": true
default should be false for `use_disktheory`. We also have a potential problem is `use_aerodyn` *and* `use_disktheory` are true. Ideally the disk theory option should go in turbine.json as a rotor type ("fea,", "fpm", "rigid", "disk").

2023-09-22 14:19 UTC, tridelat commented on data/IEA15MW/turbine.json
> -    "type": "fea",
Default should remain here for tests.

2023-09-30 06:15 UTC, mattcapa commented on src/aero/disk.cpp
disk.cpp removed

2023-09-30 06:17 UTC, mattcapa commented on src/aero/rotor_aero.cpp
> +
done

2023-09-30 06:36 UTC, mattcapa commented on src/commons/utils.cpp
> +
done

2023-09-30 06:36 UTC, mattcapa commented on src/commons/utils.cpp
> +
done

2023-09-30 06:38 UTC, mattcapa commented on src/io/read_json.cpp
> +    // std::cout<<perf_json.at("infile")<<std::endl;
done

2023-09-30 07:25 UTC, mattcapa commented on data/IEA15MW/main.json
> +      "use_disktheory": true
ok, it's done and it works

2023-09-30 07:25 UTC, mattcapa commented on src/io/read_rotor_perf.cpp
> +
ok

2023-09-30 07:26 UTC, mattcapa commented on src/io/read_rotor_perf.cpp
> +    //	const double PI = 4.0 * atan(1.0);
ok

2023-09-30 07:27 UTC, mattcapa commented on src/main.cpp
> +
done

2023-09-30 07:28 UTC, mattcapa commented on src/io/read_rotor_perf.cpp
> +        // std::cout<<TSROut<<std::endl;
done

2023-09-30 07:28 UTC, mattcapa commented on src/io/read_rotor_perf.cpp
> +            // std::cout<<line<<std::endl;
ok

2023-09-30 07:32 UTC, mattcapa commented on data/IEA15MW/turbine.json
> -    "type": "fea",
ok, done

2023-09-30 07:32 UTC, mattcapa commented on data/IEA15MW/controller/Cp_Ct_Cq.IEA15MW.txt
> +0.0    2.5    3.0    3.5    4.0    4.5    5.0    5.5    6.0    6.5    7.0    7.5    8.0    8.5    9.0    9.5    10.0    10.5    11.0    11.5    12.0    12.5    13.0    13.5    14.0    14.5
ok, it is back to normal

2023-09-30 07:33 UTC, mattcapa commented on data/IEA15MW/main.json
ok, back to normal. I generated other files for my test (turbine_disk.json)

2023-10-09 12:19 UTC, mattcapa commented on src/aero/rotor_aero.cpp
> +    // Eigen::VectorXd pitch_list;
ok solved

2023-10-09 12:22 UTC, mattcapa commented
All the reviews taken into account.

2023-10-11 14:25 UTC, mattcapa commented
The test case works now. Everything should be ready for the merge

2023-10-11 14:56 UTC, tridelat approved these changes
All good!

2023-10-11 15:31 UTC, merged