Use spdlog for logging simulation setup and outputs
Total-RD/seahowl pull request #90
Opened 2023-10-17 11:19 UTC by tridelat

This PR adds logging with different levels (trace, debug, info, warn, error, critical) through spdlog.

2023-10-17 11:55 UTC, MaxPal commented on CMakeLists.txt
> +target_link_libraries(seahowl_driver PRIVATE seahowl_core nlohmann_json::nlohmann_json ${CHRONO_LIBRARIES} spdlog::spdlog)
No need this dependency if a public dependency of seahowl_core

2023-10-17 15:21 UTC, tridelat commented on CMakeLists.txt
> +target_link_libraries(seahowl_driver PRIVATE seahowl_core nlohmann_json::nlohmann_json ${CHRONO_LIBRARIES} spdlog::spdlog)
After discussion, keeping it as a private dependency here (reason it is included here as private is because it is used in seahowl_driver but might not be used in other targets).

2023-10-20 15:14 UTC, MaxPal requested changes

2023-10-20 15:14 UTC, MaxPal commented on src/aero/blade_aero.cpp
> +        exit(1);
Brutal exit from a library is a bad idea.

... a throw. Let the user have the option to do what he wants.
Example: if you are in a parallel MPI soft you should exit in a clean way like releasing the ressources allocated (network ...)

2023-10-23 07:39 UTC, tridelat commented on src/aero/blade_aero.cpp
> +        exit(1);
Good point, the throw statements have been reintroduced and are caught in main now.

2023-10-23 07:48 UTC, MaxPal approved these changes

2023-10-23 07:51 UTC, merged